// Generated by CoffeeScript 1.6.3
(function($) {
  /*
  attaching to $ instead of $.fn, since $.fn returns a jQuery object of the selector
  */

  $.liveRef = function(selector) {
    var $liveRefcontext, combinator, liveRefMethod, liveRefSelector, splitted, _ref;
    splitted = selector.trim().replace(/\s{2,}/g, ' ').replace(RegExp(" > ", "g"), ">").replace(RegExp(" >", "g"), ">").replace(/> /g, ">").replace(/>/g, "@>@").replace(RegExp(" \\+ ", "g"), "+").replace(RegExp(" \\+", "g"), "+").replace(/\+ /g, "+").replace(/\+/g, "@+@").replace(RegExp(" ~ ", "g"), "~").replace(RegExp(" ~", "g"), "~").replace(/~ /g, "~").replace(/~/g, "@~@").replace(RegExp(" ", "g"), "@ @").split("@");
    if ((_ref = splitted[splitted.length - 1]) === " " || _ref === ">" || _ref === "+" || _ref === "~") {
      splitted.pop();
    }
    if (splitted.length >= 3) {
      liveRefSelector = splitted.pop();
      combinator = splitted.pop();
      liveRefMethod = (function() {
        switch (false) {
          case combinator !== " ":
            return "find";
          case combinator !== "+":
            return "next";
          case combinator !== ">":
            return "children";
          case combinator !== "~":
            return "nextSiblings";
        }
      })();
      $liveRefcontext = $(splitted.join(""));
    } else {
      liveRefSelector = splitted[0];
      liveRefMethod = "find";
      $liveRefcontext = $("body");
    }
    return (function() {
      return $liveRefcontext[liveRefMethod](liveRefSelector);
    })();
  };
  return $.fn.extend({
    laterSiblings: function(selector) {
      var $parentChildren, index, matches;
      selector = selector || function() {
        return true;
      };
      $parentChildren = this.parent().children();
      index = $parentChildren.index(this);
      matches = [];
      while (index < $parentChildren.length) {
        index++;
        if ($parentChildren.eq(index).is(selector)) {
          matches.push($parentChildren[index]);
        }
      }
      return $(matches);
    }
  });
})(jQuery);
