// Generated by CoffeeScript 1.6.3
(function() {
  $(function() {
    var $liveAdd, $liveList, $liveRef, $liveToggle, $vanillaAdd, $vanillaList, $vanillaRef, $vanillaToggle, listItem;
    $liveRef = $.liveRef(".with-plugin li");
    $vanillaRef = $(".without-plugin li");
    $liveList = $(".with-plugin ul");
    $vanillaList = $(".without-plugin ul");
    $liveAdd = $(".with-plugin .add-button");
    $vanillaAdd = $(".without-plugin .add-button");
    $liveToggle = $(".with-plugin .get-button");
    $vanillaToggle = $(".without-plugin .get-button");
    listItem = $vanillaRef[0].outerHTML;
    $liveAdd.on("click", function() {
      return $liveList.append($(listItem));
    });
    $vanillaAdd.on("click", function() {
      return $vanillaList.append($(listItem));
    });
    $liveToggle.on("click", function() {
      return $liveRef().toggleClass("halo");
    });
    $vanillaToggle.on("click", function() {
      return $vanillaRef.toggleClass("halo");
    });
  });

}).call(this);
