// Generated by CoffeeScript 1.6.3
(function() {
  $(function() {
    var $listItem, $listItems, $liveAdd, $liveList, $liveRef, $liveToggle, $vanillaAdd, $vanillaList, $vanillaRef, $vanillaToggle;
    $liveRef = $.liveRef(".with-plugin li");
    $vanillaRef = $(".without-plugin li");
    $liveList = $(".with-plugin ul");
    $vanillaList = $(".without-plugin ul");
    $liveAdd = $(".with-plugin .add-button");
    $vanillaAdd = $(".without-plugin .add-button");
    $liveToggle = $(".with-plugin .get-button");
    $vanillaToggle = $(".without-plugin .get-button");
    $listItem = $vanillaRef.eq(0).clone();
    $liveAdd.on("click", function() {
      return $liveList.append($listItem.clone());
    });
    $vanillaAdd.on("click", function() {
      return $vanillaList.append($listItem.clone());
    });
    $liveToggle.on("click", function() {
      return $liveRef().toggleClass("halo");
    });
    $vanillaToggle.on("click", function() {
      return $vanillaRef.toggleClass("halo");
    });
    return $listItems = $(".demo section").on("click", "li", function() {
      return $(this).remove();
    });
  });

}).call(this);
